name: Backend CI/CD

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Lint code
        run: flake8 backend/

      - name: Run tests
        run: pytest backend/

      - name: Deploy backend (Docker)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t my-backend-app backend/
          docker tag my-backend-app my-docker-repo/my-backend-app:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push my-docker-repo/my-backend-app:latest
