name: Docker Compose Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      frontend:
        image: frontend_image
        ports:
          - "3000:3000"

      backend:
        image: backend_image
        ports:
          - "5000:5000"

      ml_model:
        image: ml_model_image
        ports:
          - "5001:5001"